version = 0.1
[default.deploy.parameters]
stack_name = "sam-event-source"
resolve_s3 = true
s3_prefix = "sam-event-source"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
